name: Optimize Images

on:
  push:
    paths:
      - 'images/**'
  workflow_dispatch:

jobs:
  build:
    name: Compress and Convert Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Automatic Image Optimization
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
